#!/bin/bash
# Modify MapScreen.kt to add Save Route button and dialog

sed -i '/val lifecycleOwner = LocalLifecycleOwner.current/a \    var showSaveRouteDialog by remember { mutableStateOf(false) }\n    var routeNameToSave by remember { mutableStateOf("") }' app/src/main/java/com/example/mockgps/ui/map/MapScreen.kt

sed -i 's/IconButton(onClick = onNavigateToSavedLocations) {/IconButton(onClick = onNavigateToRoutes) {\n                        Icon(Icons.Default.List, contentDescription = "Saved Routes")\n                    }\n                    IconButton(onClick = onNavigateToSavedLocations) {/' app/src/main/java/com/example/mockgps/ui/map/MapScreen.kt

sed -i '/Button(onClick = { viewModel.addWaypoint() }) {/i \                        if (uiState.waypoints.size >= 2) {\n                            Button(onClick = { showSaveRouteDialog = true }) {\n                                Text("Save Route")\n                            }\n                        }' app/src/main/java/com/example/mockgps/ui/map/MapScreen.kt

# Add Save Route Dialog at the end of MapScreen before the error dialog
sed -i '/if (uiState.mockError != null) {/i \    if (showSaveRouteDialog) {\n        AlertDialog(\n            onDismissRequest = { showSaveRouteDialog = false },\n            title = { Text("Save Route") },\n            text = {\n                OutlinedTextField(\n                    value = routeNameToSave,\n                    onValueChange = { if (it.length <= 40) routeNameToSave = it },\n                    label = { Text("Route Name") },\n                    singleLine = true\n                )\n            },\n            confirmButton = {\n                Button(\n                    onClick = {\n                        if (routeNameToSave.trim().isNotEmpty()) {\n                            viewModel.saveRoute(routeNameToSave.trim())\n                            showSaveRouteDialog = false\n                            routeNameToSave = ""\n                        }\n                    },\n                    enabled = routeNameToSave.trim().isNotEmpty()\n                ) {\n                    Text("Save")\n                }\n            },\n            dismissButton = {\n                TextButton(onClick = { showSaveRouteDialog = false }) {\n                    Text("Cancel")\n                }\n            }\n        )\n    }\n' app/src/main/java/com/example/mockgps/ui/map/MapScreen.kt
